In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [3]:
from sklearn.svm import LinearSVC
from sklearn.svm import SVC 

In [63]:
# 배열 csv 생성
# for _ in range(1,11):
#     rssi_csv = open("rssi_array_"+str(_)+".csv", "w")
#     corridor = pd.read_csv("corridor_"+str(_)+".csv")
#     rssi = corridor['RSSI']
#     for i in range(996): 
#         rssi_csv.write(str(_)+','+str(rssi[i])+','+str(rssi[i+1])+','+str(rssi[i+2])+','+str(rssi[i+3])+','+str(rssi[i+4])+'\n')
# rssi_csv.close()

In [4]:
input_file = "rssi_array.csv"
df = pd.read_csv(input_file, header=None)

In [5]:
df = df.to_numpy()
df

array([[  1, -40, -42, -40, -41, -39],
       [  1, -42, -40, -41, -39, -40],
       [  1, -40, -41, -39, -40, -39],
       ...,
       [ 10, -51, -51, -48, -51, -49],
       [ 10, -51, -48, -51, -49, -52],
       [ 10, -48, -51, -49, -52, -52]], dtype=int64)

In [6]:
df[0]

array([  1, -40, -42, -40, -41, -39], dtype=int64)

In [7]:
x = df[:, 1:]
y = df[:, 0]

In [8]:
x

array([[-40, -42, -40, -41, -39],
       [-42, -40, -41, -39, -40],
       [-40, -41, -39, -40, -39],
       ...,
       [-51, -51, -48, -51, -49],
       [-51, -48, -51, -49, -52],
       [-48, -51, -49, -52, -52]], dtype=int64)

In [9]:
y

array([ 1,  1,  1, ..., 10, 10, 10], dtype=int64)

In [75]:
poly_kernel_svm_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("svm_clf", SVC(kernel="poly", degree=10, coef0=10, C=1))
])

In [ ]:
m = cross_val_score(poly_kernel_svm_clf, x, y, cv=10, scoring="accuracy")
print(np.mean(m))

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [11]:
from sklearn.ensemble import RandomForestClassifier

rnd = RandomForestClassifier(n_estimators=1000, max_leaf_nodes=16, n_jobs=-1,random_state=42)
rnd.fit(x,y)

m = cross_val_score(rnd, x, y, cv=10, scoring="accuracy")
print(np.mean(m))

0.4829
