In [32]:
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

df = pd.read_csv('./distance_RSSI.csv')
df

distance  RSSI
0          0.1   -31
1          0.1   -35
2          0.1   -37
3          0.1   -18
4          0.1   -23
...        ...   ...
5009       1.0   -57
5010       1.0   -52
5011       1.0   -48
5012       1.0   -53
5013       1.0   -56

[5014 rows x 2 columns]

In [33]:
df.distance.unique()

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [34]:
df['distance'].value_counts()

0.2    505
0.6    503
0.4    502
0.5    502
0.1    502
0.9    500
0.3    500
1.0    500
0.7    500
0.8    500
Name: distance, dtype: int64

In [60]:
train = df.RSSI[:]
label = df.distance[:]

In [61]:
def create_dataset(signal_data, label, window_size=1):
    dataX, dataY = [], []
    for i in range(0, len(signal_data), window_size):
        dataX.append(signal_data[i:(i+window_size)])
        dataY.append(label[i])
    return np.array(dataX), np.array(dataY)

In [62]:
import numpy as np
x_train, y_train = create_dataset(train, label)
x_train_df = pd.DataFrame(x_train)

In [63]:
print(train[0])

-31


In [64]:
print(x_train_df)

       0
0    -31
1    -35
2    -37
3    -18
4    -23
...   ..
5009 -57
5010 -52
5011 -48
5012 -53
5013 -56

[5014 rows x 1 columns]


In [74]:
print(y_train)

[0.1 0.1 0.1 ... 1.  1.  1. ]


In [75]:
print(label[0])

0.1


In [76]:
from sklearn.ensemble import RandomForestClassifier
forset_clf = RandomForestClassifier(n_estimators=10, random_state=42)

In [77]:
train.values

array([-31, -35, -37, ..., -48, -53, -56], dtype=int64)

In [78]:
label.values

array([0.1, 0.1, 0.1, ..., 1. , 1. , 1. ])

In [80]:
df = df.astype({'distance':'int'})

In [84]:
def display_scores(scores):
   print("Scores:", scores)
   print("Mean:", scores.mean())
   print("Standard deviation:", scores.std())

## 결정트리회귀

In [82]:
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor(random_state=42)
tree_reg.fit(x_train_df, y_train)

DecisionTreeRegressor(random_state=42)

In [133]:
tree_reg.score(x_train_df, y_train)

0.3807193948604395

In [134]:
print("Predictions:", xgb_reg.predict(x_train_df))

Predictions: [0.21148573 0.5063561  0.379316   ... 0.58439094 0.7082172  0.6972829 ]


In [135]:
print("Labels:", y_train)

Labels: [0.1 0.1 0.1 ... 1.  1.  1. ]


In [83]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(tree_reg, x_train_df, y_train, scoring="neg_mean_squared_error", cv=10)
tree_rmse_scores = np.sqrt(-scores)

In [85]:
display_scores(tree_rmse_scores)

Scores: [0.38847422 0.32733836 0.22322495 0.20571704 0.20054307 0.13445588
 0.21604697 0.23243791 0.32187875 0.42360839]
Mean: 0.26737255324818043
Standard deviation: 0.08796604739060923


## 선형회귀

In [87]:
from sklearn.linear_model import LinearRegression
lr_reg= LinearRegression()
lr_reg.fit(x_train_df, y_train)

LinearRegression()

In [89]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(lr_reg, x_train_df, y_train, scoring="neg_mean_squared_error", cv=10)
lr_rmse_scores = np.sqrt(-scores)

In [90]:
display_scores(lr_rmse_scores)

Scores: [0.34869189 0.31775111 0.20390167 0.18434916 0.20764714 0.1017366
 0.22704082 0.26574466 0.34363961 0.40096754]
Mean: 0.26014701867404944
Standard deviation: 0.08708970314371574


In [132]:
lr_reg.score(x_train_df, y_train)

0.27741273778268516

In [100]:
print(x_train_df)

       0
0    -31
1    -35
2    -37
3    -18
4    -23
...   ..
5009 -57
5010 -52
5011 -48
5012 -53
5013 -56

[5014 rows x 1 columns]


In [98]:
print("Predictions:", lr_reg.predict(x_train_df))

Predictions: [0.33949573 0.40037566 0.43081563 ... 0.59823545 0.67433537 0.71999532]


In [99]:
print("Labels:", y_train)

Labels: [0.1 0.1 0.1 ... 1.  1.  1. ]


## XGB 회귀

In [153]:
import xgboost as xgb

xgb_reg = xgb.XGBRegressor(n_estimators=550)
xgb_reg.fit(x_train_df, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=550, n_jobs=8,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [154]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(xgb_reg, x_train_df, y_train, scoring="neg_mean_squared_error", cv=10)
xgb_rmse_scores = np.sqrt(-scores)

In [155]:
display_scores(xgb_rmse_scores)

Scores: [0.39598135 0.32732994 0.22319807 0.20569515 0.20053271 0.13440577
 0.21602427 0.23244066 0.32188863 0.42360431]
Mean: 0.26811008598681835
Standard deviation: 0.08903378012292984


In [156]:
xgb_reg.score(x_train_df, y_train) 

0.38071925918600547

In [157]:
print("Predictions:", xgb_reg.predict(x_train_df))

Predictions: [0.21148573 0.5063561  0.379316   ... 0.58439094 0.7082172  0.6972829 ]


In [147]:
print("Labels:", y_train)

Labels: [0.1 0.1 0.1 ... 1.  1.  1. ]
